### ISSUE TITLE
Failed to call service number/set_value

### ISSUE THREAD

**Issue by sooperdoopa** [brmccrary/nuvo_simple#4]
After update to 2024.7.2, the bass/treble controls in mini media player shows this error

Failed to call service number/set_value. Caught blocking call to sleep with args (0.1,) inside the event loop by custom integration 'nuvo_simple' at custom_components/nuvo_simple/number.py, line 114: self._nuvo.set_bass(self._zone_id, value). (offender: /usr/local/lib/python3.12/site-packages/nuvo_simple/__init__.py, line 745: time.sleep(0.1) #Must wait in between commands for MPU to process), please create a bug report at https://github.com/brmccrary/nuvo-simple/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

**Comment by brmccrary** [comment]
I had noticed this today as well.  It has affected some built-in integrations I use as well.  Fortunately, even though the service fails, it should still at least set the value on the Nuvo.   This is a delay to keep the MPU/command processor on the Nuvo from occasionally crashing and resetting the whole unit if it gets commands too quickly.  It looks like fixing this will take some work, but I will fix it as soon as I can.

**Comment by sooperdoopa** [comment]
All good, thanks Barry.

**Comment by brmccrary** [comment]
Fixed in v1.3.1
